---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:15.0.2
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: admin