---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlistservice
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playlistservice
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: playlistservice
    spec:
      containers:
        - name: playlistservice
          image: sioravw/playlistservice:latest
          ports:
            - name: http
              containerPort: 8082
          resources:
            requests:
              cpu: 150m
              memory: 300Mi
            limits:
              cpu: 150m
              memory: 300Mi