apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: playlistservicehpa
  namespace: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: playlistservice
  minReplicas: 1
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75