---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-broker
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-broker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: message-broker
    spec:
      containers:
        - name: message-broker
          image: rabbitmq:3.8-management
          ports:
            - name: tcp
              containerPort: 5672
            - name: http
              containerPort: 15672