---
apiVersion: v1
kind: Service
metadata:
  name: message-broker
  namespace: backend
spec:
  ports:
    - name: tcp
      protocol: TCP
      port: 5672
      targetPort: http
    - name: http
      port: 15672
  selector:
    app: message-broker