---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: sioravw/userservice:latest
          ports:
            - name: http
              containerPort: 8081
          resources:
            requests:
              cpu: 150m
              memory: 250Mi
            limits:
              cpu: 150m
              memory: 250Mi