name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dj-collab

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=djcollabback