name: Docker Image CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dj-collab

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11.0.2
      uses: actions/setup-java@v1
      with:
        java-version: 11.0
    
    - name: maven package
      run: mvn package --file pom.xml
      
    - name: Set up kubectl
      uses: matootie/dokube@v1.4.0
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
        clusterName: djcollab
        
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./dj-collab
        push: true
        tags: sioravw/userservice:latest
        
    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl apply -f nginx/UserServiceDeployment.yaml